apiVersion: v1
kind: Service
metadata:
    name: kubeservice
spec:
    selector:
        app: kubetest
    ports:
        - port: 80
          targetPort: 8080
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubetest
spec:
    replicas: 5
    selector:
        matchLabels:
            app: kubetest
    template:
        metadata:
            labels:
                app: kubetest
        spec:
            containers:
                - name: kubecontainer
                  image: santinieto/backend_iii:0.0.1
                  ports:
                      - containerPort: 8080
                  # env:
                  #   - name: MONGO_URI
                  #     value: mongodb+srv://admin:admin@cluster0.xibok.mongodb.net/coderhouse
                  imagePullPolicy: Always
